# Generated by Django 4.2.11 on 2024-04-14 02:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0005_alter_employee_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('p', 'Present'), ('a', 'Absent'), ('al', 'Annual Leave'), ('sl', 'Sick Leave'), ('ol', 'Other Leave')], max_length=3)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_management.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
