# Generated by Django 4.2.11 on 2024-04-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0006_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('AL', 'Annual Leave'), ('SL', 'Sick Leave'), ('OL', 'Other Leave')], max_length=2),
        ),
    ]
