# Generated by Django 4.2.11 on 2024-04-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0007_alter_attendance_date_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/{employee.id}'),
        ),
    ]
