# Generated by Django 4.2.11 on 2024-04-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0009_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
