# Generated by Django 4.2.11 on 2024-04-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0011_attendance_marked_by_attendance_marked_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance2',
        ),
    ]
