# Generated by Django 4.2.11 on 2024-08-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0015_leaverecord_leavetype_remove_leaverequest_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='annual_leave_balance',
            new_name='accrued_annual_leave',
        ),
        migrations.RenameField(
            model_name='leaverecord',
            old_name='description',
            new_name='reason',
        ),
        migrations.AddField(
            model_name='employee',
            name='used_annual_leave',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
